### ISSUE TITLE
Yandex GPS tracks

### ISSUE THREAD

**Issue by bertt** [bertt/wmts#3]
Copied from https://github.com/bertt/wmts/issues/2#issuecomment-397580438 by @luiswoo

"Hi, is it possible to add gps tracks by Yandex (n.maps.yandex.ru)?
https://core-gpstiles.maps.yandex.net/tiles?style=point&x=37275&y=19294&z=16
https://core-gpstiles.maps.yandex.net/tiles?style=red_combined&x=37268&y=19297&z=16

"ygpx": { \
     "name": "yandex gps point",
     "prefix": "ygpx",			# tile directory
     "ext": "png",			# tile images extension
     "scalable": False,			# could zN tile be constructed of four z(N+1) tiles
     "fetch": fetchers.Tile,		# function that fetches given tile. should return None if tile wasn't fetched
     "remote_url": "https://gps-tiles.maps.yandex.net/tiles?style=point&x=%s&y=%s&z=%s",
     "transform_tile_number": lambda z,x,y: (x,y,z-1),
     "dead_tile": install_path + "yandex_nxt.jpg",
     "proj": "EPSG:3395",
},\
"ygpx_red_combined": { \
     "name": "yandex gps red_combined",
     "prefix": "ygpx_red_combined",		# tile directory
     "ext": "png",				# tile images extension
     "scalable": False,				# could zN tile be constructed of four z(N+1) tiles
     "fetch": fetchers.Tile,			# function that fetches given tile. should return None if tile wasn't fetched
     "remote_url": "https://gps-tiles.maps.yandex.net/tiles?style=red_combined&x=%s&y=%s&z=%s",
     "transform_tile_number": lambda z,x,y: (x,y,z-1),
     "dead_tile": install_path + "yandex_nxt.jpg",
     "proj": "EPSG:3395",
},\
^
this is for TWMS https://github.com/Komzpa/twms

https://n.maps.yandex.ru/#!/help?z=16&ll=24.740202%2C59.432151&l=nk%23sat"

**Comment by luiswoo** [comment]
already added https://github.com/luiswoo/wmts/blob/gh-pages/capabilities/yandex.xml

**Comment by bertt** [comment]
Can you send a pr?

**Comment by luiswoo** [comment]
No, because of my own, about zero knowledge of English, I can hardly understand how to do it.

**Comment by bertt** [comment]
Added Yandex gps points in https://github.com/bertt/wmts/commit/141b1cba8a69ea0dbc69aae9a9f9e0e8deae6d7a 

and closing this issue
